"""Iter 97 (review 5.3 / 5.4): one calibration, PRD-shaped, shared by gate and server.

Pins: chronological hold-out of the last ~20% of check-in TIMES; early stop
with patience; accept only if held-out loss improves (else the initial
embedding comes back untouched); a non-zero default prior weight; a soft norm
penalty with only a large safety clamp; Huber residuals; masks and the real
start time reaching the integrator; and the benchmark and the server binding
the SAME function.
"""

from __future__ import annotations

import os
import unittest
from unittest import mock

import numpy as np
import torch

from pulse import benchmark as bm
from pulse import calibration as cal
from pulse import server
from pulse.calibration import (
    CalibrationSettings,
    MeasurementPoint,
    SoftEvidence,
    calibrate_embedding,
    huber,
    split_check_ins,
)
from pulse.model import ModularPhysiologyNetwork, integrate
from pulse.modules.gut import MealEvent
from pulse.types import MARKER_INDEX, NORM_CENTER


def _model() -> ModularPhysiologyNetwork:
    torch.manual_seed(0)
    m = ModularPhysiologyNetwork()
    m.eval()
    for p in m.parameters():
        p.requires_grad_(False)
    return m


class TestPieces(unittest.TestCase):
    def test_split_is_chronological_last_fifth(self) -> None:
        times = [0, 60, 120, 180, 240, 300, 360, 420, 480, 540]
        train, val = split_check_ins(times, 0.2)
        self.assertEqual(val, {480, 540})
        self.assertEqual(train, set(times[:-2]))
        # duplicates (several markers at one time) count once
        train, val = split_check_ins([0, 0, 60, 60, 120, 120], 0.2)
        self.assertEqual(val, {120})
        # too few times / disabled
        self.assertEqual(split_check_ins([0], 0.2), ({0}, set()))
        self.assertEqual(split_check_ins(times, 0.0), (set(times), set()))
        # never eats every train time
        self.assertEqual(split_check_ins([0, 60], 0.9), ({0}, {60}))

    def test_huber_equals_mse_inside_delta(self) -> None:
        r = torch.tensor([0.5, -0.5, 3.0])
        out = huber(r, 1.0)
        self.assertAlmostEqual(float(out[0]), 0.25, places=6)
        self.assertAlmostEqual(float(out[1]), 0.25, places=6)
        self.assertAlmostEqual(float(out[2]), 1.0 * (2 * 3.0 - 1.0), places=6)  # 5, not 9
        self.assertTrue(torch.allclose(huber(r, float("inf")), r.pow(2)))

    def test_defaults_are_prd_shaped_and_env_overridable(self) -> None:
        st = CalibrationSettings()
        self.assertGreater(st.prior_weight, 0.0)
        self.assertEqual(st.prior_weight, 0.25)
        self.assertGreater(st.holdout_fraction, 0.0)
        self.assertGreater(st.patience, 0)
        self.assertGreater(st.soft_norm_weight, 0.0)
        self.assertGreater(st.max_norm, 3.0)  # the old clamp is no longer the regularizer
        with mock.patch.dict(os.environ, {"PULSE_BENCHMARK_PRIOR_WEIGHT": "0.7",
                                          "PULSE_BENCHMARK_SOFT_NORM_WEIGHT": "0.05"}):
            env = CalibrationSettings.from_env()
        self.assertEqual(env.prior_weight, 0.7)
        self.assertEqual(env.soft_norm_weight, 0.05)
        self.assertIn("prior_weight", st.as_dict())


class TestAlgorithm(unittest.TestCase):
    def setUp(self) -> None:
        self.model = _model()
        self.init = torch.tensor(NORM_CENTER, dtype=torch.float32)
        self.dur = 420
        self.t0 = 21.0 * 60.0
        g = torch.Generator().manual_seed(3)
        self.sw = (torch.rand(self.dur, generator=g) > 0.5).float()
        self.act = torch.rand(self.dur, generator=g) * 0.2
        self.meals = [MealEvent(time=30.0, carbs=50.0, fats=10.0, proteins=15.0)]
        self.prior_mean = torch.randn(self.model.embedding_dim, generator=g) * 0.1
        self.prior_std = torch.full((self.model.embedding_dim,), 0.15)
        self.truth_emb = self.prior_mean + 0.4 * torch.randn(self.model.embedding_dim, generator=g)

    def _truth_obs(self, emb: torch.Tensor, times, markers=("glucose", "hr")) -> list[MeasurementPoint]:
        with torch.no_grad():
            traj = integrate(model=self.model, initial_state=self.init, embedding=emb,
                             n_steps=self.dur, dt=1.0, start_time_minutes=self.t0,
                             meals=self.meals, sleep_wake=self.sw, activity=self.act)
        return [MeasurementPoint(time=t, marker_id=m, value=float(traj[t, MARKER_INDEX[m]]))
                for t in times for m in markers]

    def test_perfect_fit_at_start_is_not_accepted(self) -> None:
        # Observations generated by the initial embedding: nothing can improve
        # the held-out loss, so the answer must be the initial embedding.
        obs = self._truth_obs(self.prior_mean, range(0, 400, 40))
        res = calibrate_embedding(
            self.model, obs, self.init, self.meals, self.dur, start_time_minutes=self.t0,
            sleep_wake=self.sw, activity=self.act, prior_mean=self.prior_mean,
            prior_std=self.prior_std,
            settings=CalibrationSettings(max_steps=12, lr=0.05, patience=4),
        )
        self.assertFalse(res.accepted)
        self.assertEqual(res.reason, "no_improvement")
        self.assertTrue(torch.allclose(res.embedding, self.prior_mean))
        self.assertEqual(res.n_val_obs, 4)  # 10 times -> 2 held out x 2 markers
        self.assertEqual(res.n_train_obs, 16)
        self.assertLessEqual(res.n_steps, 12)

    def test_early_stop_and_acceptance_when_evidence_improves(self) -> None:
        obs = self._truth_obs(self.truth_emb, range(0, 400, 40))
        res = calibrate_embedding(
            self.model, obs, self.init, self.meals, self.dur, start_time_minutes=self.t0,
            sleep_wake=self.sw, activity=self.act, prior_mean=self.prior_mean,
            prior_std=self.prior_std,
            settings=CalibrationSettings(max_steps=40, lr=0.05, patience=6, prior_weight=0.05),
        )
        self.assertTrue(np.isfinite(res.baseline_val_loss))
        if res.accepted:
            self.assertLess(res.val_loss, res.baseline_val_loss)
            self.assertGreater(res.best_step, 0)
            self.assertFalse(torch.allclose(res.embedding, self.prior_mean))
        else:
            self.assertTrue(torch.allclose(res.embedding, self.prior_mean))
        # early stop: patience bounds the run after the best step
        self.assertLessEqual(res.n_steps, res.best_step + 6 + 1 if res.accepted else 40)

    def test_too_few_check_in_times_returns_initial(self) -> None:
        obs = self._truth_obs(self.truth_emb, [100])
        res = calibrate_embedding(
            self.model, obs, self.init, self.meals, self.dur, start_time_minutes=self.t0,
            prior_mean=self.prior_mean, prior_std=self.prior_std,
            settings=CalibrationSettings(max_steps=5),
        )
        self.assertFalse(res.accepted)
        self.assertEqual(res.reason, "too_few_check_ins")
        self.assertTrue(torch.allclose(res.embedding, self.prior_mean))

    def test_masks_and_start_time_reach_the_integrator(self) -> None:
        obs = self._truth_obs(self.truth_emb, [60, 120, 180])
        seen: list[dict] = []
        real = cal.integrate

        def spy(**kw):
            seen.append(kw)
            return real(**kw)

        with mock.patch.object(cal, "integrate", spy):
            calibrate_embedding(
                self.model, obs, self.init, self.meals, self.dur, start_time_minutes=self.t0,
                sleep_wake=self.sw, activity=self.act, prior_mean=self.prior_mean,
                prior_std=self.prior_std, settings=CalibrationSettings(max_steps=2, patience=0),
            )
        self.assertTrue(seen)
        for kw in seen:
            self.assertEqual(kw["start_time_minutes"], self.t0)
            self.assertEqual(kw["n_steps"], 181)  # continuous to the last check-in
            self.assertTrue(torch.equal(kw["sleep_wake"], self.sw[:181]))
            self.assertTrue(torch.equal(kw["activity"], self.act[:181]))
            self.assertEqual([m.time for m in kw["meals"]], [30.0])

    def test_soft_norm_replaces_hard_clamp_but_safety_clamp_holds(self) -> None:
        # Extreme targets, huge lr, no prior: the embedding runs. The hard clamp
        # at max_norm must still bound it; the soft penalty must be a penalty,
        # not a wall (norm may exceed the radius).
        obs = [MeasurementPoint(time=t, marker_id="glucose", value=400.0) for t in (30, 60, 90, 120, 150)]
        res = calibrate_embedding(
            self.model, obs, self.init, [], self.dur, start_time_minutes=self.t0,
            settings=CalibrationSettings(max_steps=25, lr=0.5, holdout_fraction=0.0, l2_weight=0.0,
                                         soft_norm_weight=0.1, soft_norm_radius=1.0, max_norm=2.5),
        )
        self.assertLessEqual(res.embedding_norm, 2.5 + 1e-5)
        res_wall = calibrate_embedding(
            self.model, obs, self.init, [], self.dur, start_time_minutes=self.t0,
            settings=CalibrationSettings(max_steps=25, lr=0.5, holdout_fraction=0.0, l2_weight=0.0,
                                         soft_norm_weight=0.0, soft_norm_radius=1.0, max_norm=1.0),
        )
        self.assertLessEqual(res_wall.embedding_norm, 1.0 + 1e-5)

    def test_prior_pulls_toward_the_population(self) -> None:
        obs = self._truth_obs(self.truth_emb, range(0, 400, 40))
        norms = {}
        for w in (0.0, 2.0):
            res = calibrate_embedding(
                self.model, obs, self.init, self.meals, self.dur, start_time_minutes=self.t0,
                sleep_wake=self.sw, activity=self.act, prior_mean=self.prior_mean,
                prior_std=self.prior_std,
                settings=CalibrationSettings(max_steps=15, lr=0.05, holdout_fraction=0.0,
                                             prior_weight=w, soft_norm_weight=0.0),
            )
            norms[w] = float((res.embedding - self.prior_mean).norm())
        self.assertLess(norms[2.0], norms[0.0])

    def test_soft_evidence_enters_the_loss(self) -> None:
        soft = [SoftEvidence(time=t, marker_id="glucose", direction="above", threshold=250.0,
                             specificity=1.0, scale=10.0) for t in (30, 60, 90)]
        loss = cal.evaluate_data_loss(self.model, self.prior_mean, [], self.init, [], self.dur,
                                      start_time_minutes=self.t0, soft_evidence=soft)
        self.assertGreater(loss, 1.0)  # glucose ~95 is far below 250: large NLL


class TestOneFunction(unittest.TestCase):
    def test_gate_and_server_bind_the_same_calibration(self) -> None:
        self.assertIs(bm._gate_calibrate, cal.calibrate_embedding)
        self.assertIs(server.shared_calibrate, cal.calibrate_embedding)

    def test_server_builds_masks_and_uses_real_start_time(self) -> None:
        cis = [
            server.CheckInInput(time=0, createdAt="x", sleepWake=1.0, activity=0.0,
                                measurements={"glucose": 95, "hr": 62}),
            server.CheckInInput(time=120, createdAt="x", sleepWake=0.0,
                                measurements={"glucose": 90, "hr": 55}),
            server.CheckInInput(time=300, createdAt="x", sleepWake=0.0, activity=0.0,
                                measurements={"glucose": 88, "hr": 54}),
            server.CheckInInput(time=420, createdAt="x", sleepWake=1.0, activity=0.3,
                                measurements={"glucose": 100, "hr": 70}),
        ]
        sw = server.build_minute_mask(None, cis, "sleepWake", 480)
        act = server.build_minute_mask(None, cis, "activity", 480)
        self.assertEqual(sw.shape[0], 480)
        self.assertEqual(float(sw[10]), 1.0)
        self.assertEqual(float(sw[200]), 0.0)
        self.assertEqual(float(sw[479]), 1.0)
        self.assertEqual(float(act[100]), 0.0)   # forward-filled from t=0
        self.assertEqual(float(act[301]), 0.0)
        self.assertAlmostEqual(float(act[450]), 0.3, places=6)
        self.assertIsNone(server.build_minute_mask(None, [], "activity", 480))
        explicit = server.build_minute_mask([0.1, 0.2], [], "activity", 5)
        np.testing.assert_allclose(explicit.numpy(), [0.1, 0.2, 0.2, 0.2, 0.2], rtol=1e-6)
        self.assertEqual(server.resolve_start_time_minutes(None), 360.0)
        self.assertEqual(server.resolve_start_time_minutes(22.5 * 60), 1350.0)

        model = _model()
        seen: list[dict] = []
        real = cal.integrate

        def spy(**kw):
            seen.append(kw)
            return real(**kw)

        init = server.initial_state_from_baseline({})
        with mock.patch.object(cal, "integrate", spy):
            res = server.calibrate_embedding(
                model=model, user_id="u", initial_embedding=torch.zeros(model.embedding_dim),
                initial_baseline={}, check_ins=cis, duration_min=480, meals=[],
                initial_state=init, enabled=True, start_time_minutes=1350.0,
                sleep_wake=sw, activity=act,
                settings=CalibrationSettings(max_steps=2, patience=0),
            )
        self.assertTrue(seen)
        for kw in seen:
            self.assertEqual(kw["start_time_minutes"], 1350.0)
            self.assertIsNotNone(kw["sleep_wake"])
            self.assertIsNotNone(kw["activity"])
        self.assertIn(res.reason, ("accepted", "no_improvement"))
        self.assertEqual(res.steps, 2)


if __name__ == "__main__":
    unittest.main()
