"""
Setpoint-supervision signal — teach the embedding→physiology map directly.

Iter 90. Per-patient embeddings are 20-odd free vectors in a 64-dim space, learned
only by reconstructing trajectories. Nothing ever told the model what a patient's
embedding *means*, and nothing encouraged the map from embedding to physiology to be
smooth, disentangled, or invertible. The benchmark nevertheless depends on inverting
exactly that map: at eval time we find a new person by gradient-descending an embedding
against their observed markers.

Measured on the iter-89 checkpoint (scripts/iter89_recovery_test.py) in the BEST CASE —
synthetic people drawn from the learned prior, their observations generated by the model
itself, so there is zero model error — calibration recovers a person's fasting glucose
setpoint *worse than simply predicting the population mean*: mean |error| 54.4 mg/dL vs
2.1 for the prior mean (skill −24.7). Both embeddings ran straight to the ‖emb‖≤3 clamp
and the recovered code was essentially orthogonal to the truth (cos = +0.08). We were not
finding the person; we were finding a point on the leash boundary.

Two causes, both addressed in iter 90. The first was the rate-constant frame bug (fixed
separately): with a fasting-glucose τ of 515 min over a ~294 min calibration window,
glucose barely leaves its initial condition regardless of Gb_emb, so the observations
carried almost no information about the setpoint and the gradient was flat. Fixing τ to
56 min alone cuts Gb recovery error 5× and unpins the embedding from the clamp.

The second is that the map was never supervised — which this signal fixes. The teacher
KNOWS every patient's true setpoints (they are the sampled PatientParams), and the model
has dedicated per-patient heads that decode exactly those quantities from the embedding:

    metabolic.glucose_baseline_net   -> Gb
    cardiovascular.setpoint_net      -> HR0, HRV0, SBP0, DBP0

Through iter 89 those targets were generated and thrown away. Here we simply supervise the
decoded values against them, in z-units so every marker contributes comparably. This
conditions the inverse problem directly: it makes each head's output mean a specific
physiological quantity (rather than whatever the reconstruction loss happened to settle
on), and it discourages entanglement, because each head is pulled toward its OWN target
instead of borrowing embedding directions from its neighbours. Combined with the correlated
teacher population (which supplies the true joint structure), the embedding now has both a
well-posed target and an honest covariance to learn.

Cost is negligible: no rollout, no integration — just the two small heads evaluated on the
patient embeddings. It therefore runs from epoch 0.

Only patients whose episode carries ground-truth setpoints are supervised (the full_body
teacher); other contributions do not simulate a whole patient and are skipped. Default
patients use the zero embedding, whose zero-init heads already decode to NORM_CENTER —
which is exactly PatientParams()'s resting state — so they need no supervision.
"""

from __future__ import annotations

from dataclasses import dataclass, field

import torch
import torch.nn as nn

from ..modules import cardiovascular as _cvs
from ..modules import metabolic as _met
from ..modules import thermoreg as _thm
from ..types import MARKER_INDEX, NORM_CENTER, NORM_SCALE
from .safe_step import accumulate_grad
from .signals import SignalContext, SignalResult, TrainingSignal, WeightSchedule

# Markers decoded by the cardiovascular setpoint head, in its state order.
_CVS_MARKERS = ("hr", "hrv", "sbp", "dbp")
_GLUCOSE = "glucose"
_TEMP = "temp"


def _z(marker: str, raw: float) -> float:
    idx = MARKER_INDEX[marker]
    return (raw - NORM_CENTER[idx]) / float(NORM_SCALE[idx])


@dataclass
class SetpointSupervisionSignal(TrainingSignal):
    """MSE, in z-units, between each patient's decoded and true resting setpoints."""

    weight: WeightSchedule = field(default_factory=lambda: WeightSchedule(0.0))
    # pid -> {marker_id: raw setpoint}. Only patients with a learned embedding row.
    targets: dict[int, dict[str, float]] = field(default_factory=dict)

    name: str = "setpoint_supervision"
    source: str = "Iter 90 recovery test: embedding->physiology map was not invertible"
    category: str = "mechanism"

    def weight_at(self, epoch: int) -> float:
        return self.weight.at(epoch)

    def compute(
        self,
        model: nn.Module,
        embeddings: nn.Embedding,
        ctx: SignalContext,
    ) -> SignalResult:
        w = self.weight_at(ctx.epoch)
        if w <= 0 or not self.targets:
            return SignalResult()

        device = ctx.device
        pids = sorted(self.targets)
        pid_t = torch.tensor(pids, dtype=torch.long, device=device)
        emb = embeddings(pid_t)  # [P, EMBEDDING_DIM]

        # --- decode the per-patient physiology the heads emit (z-units) ---
        e_met = model.embedding_projections["metabolic"](emb)
        pred_gb_z = _met._GLUCOSE_BASELINE_MAX_Z * torch.tanh(
            model.metabolic.glucose_baseline_net(e_met).squeeze(-1)
        )  # [P]
        e_cvs = model.embedding_projections["cardiovascular"](emb)
        pred_cvs_z = _cvs._CVS_BASELINE_MAX_Z * torch.tanh(
            model.cardiovascular.setpoint_net(e_cvs)
        )  # [P, 4]
        # Iter 91: thermoreg now has a per-patient setpoint head too (it was a bare MLP with no
        # restoring structure — the same gap CVS had until iter 89).
        e_thm = model.embedding_projections["thermoreg"](emb)
        pred_temp_z = _thm._TEMP_SETPOINT_MAX_Z * torch.tanh(
            model.thermoreg.setpoint_net(e_thm).squeeze(-1)
        )  # [P]

        # --- ground truth (z-units), masked per marker ---
        # Not every contribution simulates a whole patient: only full_body episodes carry
        # all five setpoints, and a partial dict must not KeyError. Build a [P, 5] target
        # and a matching mask, and average over the OBSERVED (patient, marker) pairs only.
        markers = (_GLUCOSE,) + _CVS_MARKERS + (_TEMP,)
        tgt_rows: list[list[float]] = []
        mask_rows: list[list[float]] = []
        for p in pids:
            sp = self.targets[p]
            tgt_rows.append([_z(m, sp[m]) if m in sp else 0.0 for m in markers])
            mask_rows.append([1.0 if m in sp else 0.0 for m in markers])
        tgt_z = torch.tensor(tgt_rows, dtype=torch.float32, device=device)   # [P, 6]
        mask = torch.tensor(mask_rows, dtype=torch.float32, device=device)   # [P, 6]

        pred_z = torch.cat(
            [pred_gb_z.unsqueeze(-1), pred_cvs_z, pred_temp_z.unsqueeze(-1)], dim=-1
        )  # [P, 6]

        denom = mask.sum().clamp_min(1.0)
        loss = (mask * (pred_z - tgt_z).pow(2)).sum() / denom

        sub: dict[str, float] = {"n_patients": float(len(pids))}
        with torch.no_grad():
            # Report raw-unit MAE per marker — directly comparable to the recovery test.
            for j, m in enumerate(markers):
                mj = mask[:, j]
                if float(mj.sum()) == 0.0:
                    continue
                s = float(NORM_SCALE[MARKER_INDEX[m]])
                err = ((pred_z[:, j] - tgt_z[:, j]).abs() * mj).sum() / mj.sum()
                sub[f"{m}_mae"] = float(err * s)

        accumulate_grad(
            w * loss,
            ctx,
            signal=self.name,
            extra={"raw_loss": float(loss.detach().item()), "weight": float(w), **sub},
        )
        return SignalResult(
            loss_sum=float(loss.detach().item()),
            n_units=1,
            sub_metrics=sub,
        )
