"""
Knowledge contribution protocol.

Each knowledge source generates training episodes — synthetic time series
that encode medical knowledge about specific physiological behaviors.
Episodes can target individual modules or span the full system.
"""

from dataclasses import dataclass, field
import numpy as np


@dataclass
class CouplingPrior:
    """Medical knowledge about a coupling edge's expected behavior."""
    source_marker: str
    target_marker: str
    sign: int  # +1 or -1
    magnitude_range: tuple[float, float] = (0.0, 1.0)


@dataclass
class Episode:
    """A training episode generated by a knowledge contribution.

    trajectory: np.ndarray of shape (n_steps, n_markers) — values this
                episode actually supervises. Unsupervised markers are NaN
                (training skips them; missing positions are imputed from
                typicals only for the initial state). A FullBody day tapes
                wearable vitals only; hormones are not a dense target.
    meals: list of (time, carbs, fats, proteins) tuples
    duration_min: length of the episode in minutes
    start_hour: what time of day the episode starts (for circadian context)
    sleep_wake: optional np.ndarray of shape (n_steps,) — 0=asleep, 1=awake
    activity: optional np.ndarray of shape (n_steps,) — 0=rest to 1=vigorous
    source: identifier of the knowledge contribution that generated this
    setpoints: optional {marker_id: raw resting value} — the GROUND-TRUTH per-patient
               setpoints this episode was generated from (iter 90). The generator knows
               them exactly (they are the sampled PatientParams), but through iter 89 they
               were discarded, so the per-patient embedding had to DISCOVER each patient's
               physiology from the trajectory alone. That map was never supervised and, as
               measured, is not invertible: calibration recovers a person's fasting glucose
               worse than simply predicting the population mean. Carrying the setpoints lets
               ``SetpointSupervisionSignal`` supervise the embedding's decoded physiology
               directly. ``None`` for contributions that do not model a whole patient.
    patient_params: optional {name: value} — per-patient quantities that are NOT markers,
               so they have no place in ``setpoints`` but are decoded from the embedding
               just the same (body mass; the insulin-sensitivity family). Same argument as
               ``setpoints`` one paragraph up, and the same measured failure behind it: a
               per-patient head with no ground truth is free authority, and iter 109
               measured where that ends — the glucagon-basal head walked the prior person
               from 70 to 98 pg/mL while nothing downstream moved, because every hepatic
               gate is normalized to the patient's OWN basal. The quantities here are the
               ones the teacher varies per patient and the student had to either guess or
               hold at a population constant. ``None`` as for ``setpoints``.
    """
    trajectory: np.ndarray
    meals: list[tuple[float, float, float, float]] = field(default_factory=list)
    duration_min: int = 1440
    start_hour: float = 6.0
    sleep_wake: np.ndarray | None = None
    activity: np.ndarray | None = None
    absorption_profile: np.ndarray | None = None  # (n_steps, 4): glucose/lipid/amino appearance + nutrient flag
    source: str = ""
    setpoints: dict[str, float] | None = None
    patient_params: dict[str, float] | None = None
    # Iter 91: this patient's TRUE postprandial response to a standard 75 g meal
    # (glucose_peak_rise mg/dL, glucose_time_to_peak_min). The per-patient meal AMPLITUDE
    # the student's Ra head needs -- iter-90 measured Ra frozen (std 0.01) because nothing
    # supervised it, which made calibration inflate Gb to compensate. None for contributions
    # that do not simulate a whole patient.
    meal_response: dict[str, float] | None = None


@dataclass
class KnowledgeContribution:
    """A knowledge source that generates training episodes."""
    name: str
    source: str
    description: str

    def generate_episodes(
        self,
        n_episodes: int,
        rng: np.random.Generator,
    ) -> list[Episode]:
        raise NotImplementedError

    def coupling_priors(self) -> list[CouplingPrior]:
        return []

    def trajectory_loss_mode(self) -> str:
        """Trajectory fit: 'mse' or 'huber' (softer on outliers from rough generators)."""
        return "mse"
