"""
Knowledge contribution protocol.

Each knowledge source generates training episodes — synthetic time series
that encode medical knowledge about specific physiological behaviors.
Episodes can target individual modules or span the full system.
"""

from dataclasses import dataclass, field
import numpy as np


@dataclass
class CouplingPrior:
    """Medical knowledge about a coupling edge's expected behavior."""
    source_marker: str
    target_marker: str
    sign: int  # +1 or -1
    magnitude_range: tuple[float, float] = (0.0, 1.0)


@dataclass
class Episode:
    """A training episode generated by a knowledge contribution.

    trajectory: np.ndarray of shape (n_steps, n_markers) — ground truth
                values for the markers this episode covers. Markers not
                covered by this episode have NaN values (training masks them;
                missing positions are imputed from typicals only for initial state).
    meals: list of (time, carbs, fats, proteins) tuples
    duration_min: length of the episode in minutes
    start_hour: what time of day the episode starts (for circadian context)
    sleep_wake: optional np.ndarray of shape (n_steps,) — 0=asleep, 1=awake
    activity: optional np.ndarray of shape (n_steps,) — 0=rest to 1=vigorous
    source: identifier of the knowledge contribution that generated this
    """
    trajectory: np.ndarray
    meals: list[tuple[float, float, float, float]] = field(default_factory=list)
    duration_min: int = 1440
    start_hour: float = 6.0
    sleep_wake: np.ndarray | None = None
    activity: np.ndarray | None = None
    absorption_profile: np.ndarray | None = None  # (n_steps, 4): glucose/lipid/amino appearance + nutrient flag
    source: str = ""


@dataclass
class KnowledgeContribution:
    """A knowledge source that generates training episodes."""
    name: str
    source: str
    description: str

    def generate_episodes(
        self,
        n_episodes: int,
        rng: np.random.Generator,
    ) -> list[Episode]:
        raise NotImplementedError

    def coupling_priors(self) -> list[CouplingPrior]:
        return []

    def trajectory_loss_mode(self) -> str:
        """Trajectory fit: 'mse' or 'huber' (softer on outliers from rough generators)."""
        return "mse"
