#!/usr/bin/env python3
"""Does calibrating on some markers improve prediction of markers it never saw?

PRD, *Why modularity*: "a single glucose reading doesn't just constrain glucose --
it propagates through the coupling graph", and *Success criteria*: "Coupling
amplifies information: observations on one module improve predictions for coupled
modules". PLAN D5 recorded that this had no number. This is the number.

THE EXPERIMENT. Calibrate the embedding on marker set A (the shared
``pulse.calibration.calibrate_embedding`` the gate and the server run; ``--steps``
caps its Adam steps for speed, ``--gate-settings`` lifts the cap), then predict a
DISJOINT held-out set B and compare with the honest baseline of not having
calibrated at all:

    skill[b] = 1 - MAE_calibrated[b] / MAE_prior_mean[b]

* The baseline is the PRIOR-MEAN embedding (the trained prior mean, else zeros),
  NOT persistence. The gate's skill is ``1 - MAE / max(persistence_MAE, sigma_obs)``
  (benchmark.py ``_build_per_marker``); this is the same shape with a different
  baseline, so 0 means "calibration changed nothing the held-out markers could
  feel", positive means fitting A moved B toward the truth, and NEGATIVE means
  fitting A made B worse -- the coupling is laundering error instead of carrying
  information. Both are reported plainly. Aggregation is the gate's too: MAE per
  patient (episode) first, then the mean over patients, then the ratio.
* ``skill`` is the raw ratio, the only form that is exactly 0 when nothing
  changed. ``gate`` is the benchmark.py form with the denominator floored at
  sigma_obs; it is flagged ``*`` when the prior-mean error is already under the
  sensor noise, where the floor hands out credit for being inside the noise rather
  than for amplifying anything. ``MAE_init`` is persistence from the initial state,
  the gate's own baseline for a marker calibration never saw, so a reader can see
  when the prior-mean baseline is itself worse than carrying the first reading
  forward. A marker whose prior-mean error is under 1e-4 of its NORM_SCALE is
  ``flat`` -- the model gives calibration nothing to move there -- and is left out
  of the headline and counted.

ACCEPTANCE IS PART OF THE RESULT. ``calibrate_embedding`` returns the initial
embedding unchanged unless the chronological hold-out (the last ~20% of the A
check-in TIMES) improved by 1%. A rejected window therefore scores skill exactly 0
on every marker, and the table counts them: a glucose-only window that is rarely
accepted cannot amplify anything. Do not confuse the two hold-outs: that one is
temporal, inside calibration, on the markers it was shown; B is held out by MARKER.

THE CONTROL. The markers that WERE calibrated on are scored too, at the check-in
times themselves (in-sample) and over the whole scored span. In-sample skill must
be clearly positive on synthetic patients the model generated itself; if it is not,
the probe is measuring nothing and that is the first thing to fix. A verdict line
says which.

CROSS- vs SAME-MODULE. The PRD claims transfer to COUPLED modules, so held-out
markers are tagged ``cross`` when no calibrated marker shares their module and
``same`` when one does (insulin after glucose, sbp after hr), and the headline is
split. ``same`` is the weak claim; ``cross`` is the PRD's.

CHANNELS. Calibration moves ONE shared vector, so a positive skill can arrive two
ways that the table adds together: through the coupling graph (A's module changed,
B reads it) or through the shared embedding (B's own parameters moved with the code,
or both read one upstream driver such as the gut kernel). The CHANNELS table (on by
default; ``--no-channels`` skips it) reruns the held-out rollout with the calibrated
embedding shown to only part of the model, by rerouting the per-module projections
the model already has: ``own`` (B's module only), ``coupling`` (A's modules only: B
can move only through coupling edges), ``gut`` (the gut kernel only: the shared meal
driver). The channels are not additive. If rerouting every projection does not
reproduce the plain rollout, the model reads the embedding somewhere else too, and
the table says so rather than printing a decomposition it cannot stand behind.

PART 1, SYNTHETIC PATIENTS (the clean case). Embeddings are drawn from the trained
prior (``prior_mean + prior_std * z``, as iter89_recovery_test.py does) when the
checkpoint carries one, else ``N(0, 0.1^2)``; each patient starts from their own
setpoints, and their observations and the held-out truth are generated by the
model ITSELF with explicit awake/rest inputs: no model error, no sensor noise
(``--noise`` adds some to A's observations), every input known. A zero or negative
number here is therefore decisive about the model's own structure -- better data
cannot fix it -- while a positive one only says the structure CAN transfer. Two
limits: a diagonal prior samples independent coordinates, so it does not sample the
correlations a real population has (``--patients-from table`` uses the checkpoint's
trained rows instead, which have them but were trained on); and 3 patients is a
machinery check, not a confidence interval (one is printed from 6).

PART 2, REAL EPISODES (``--dataset``). Per episode: calibrate on A's check-ins with
the episode's masks and start time, score the markers outside A on the episode's own
measurements -- B's calibration-window check-ins (``window``) and the eval
measurements (``ahead``) -- e.g. calibrate on glucose, score hr on the ``cgm_real``
nights. ``cgm_real`` is 14 nights of ONE subject: read it as n=1 (the output counts
subjects).

WHAT AN UNTRAINED MODEL'S NUMBERS ARE. No trained checkpoint is needed to run this,
and without one the numbers measure the MACHINERY (calibrate -> accept or reject ->
predict -> score -> control), not the model. A fresh ``ModularPhysiologyNetwork`` has
every per-person head zero-initialised (15 all-zero output matrices at this commit), so
"every embedding is the median person" and the embedding reaches the trajectory only
through the gut kernel and the appetite dynamics. Measured (seed 0, 8 patients at
sd 0.1, 120 min): the prior-mean prediction is off by 0.048 mg/dL of glucose, 0.051
uU/mL of insulin, 0.021 pg/mL of ghrelin -- and by exactly 0 in cortisol, acth, sbp,
dbp, rr and spo2. The probe finds those held-out markers ``flat`` and says so.
``--authority STD`` re-draws the zero matrices from N(0, STD^2) so the embedding can
move every module (at 0.3: glucose 0.63 mg/dL, sbp 0.99 mmHg, hr 0.73 bpm); that
exercises the whole path on a model that is still untrained. What it showed
(3 model seeds x 2 sets x 3 patients, plus one 8-patient run): a clearly positive
control (in-sample skill +0.57 to +0.90), calibration accepted in 22 of 26 windows,
and a held-out headline that is indistinguishable from zero with a sign that changes
with the seed (-0.14 to +0.16 over the six seed x set cells, mean +0.02; the 8-patient
interval spans 0), because the shared projections are random.
None of this says anything about whether a TRAINED model amplifies information. The
only thing an untrained run can establish is that the instrument works.

COST. One Adam step is one forward+backward over the whole calibration window, ~0.5-1
s per 60 minutes on a quiet core and several times that on a loaded box, so the defaults
are small: 3 patients x 2 sets, 120 min, 16 Adam steps, channels on = ~90 s alone on a
4-core box at load ~15 (~8 min when five runs share it; the first backward in a process
can cost minutes more on a cold box). Scale up with ``--patients``, ``--steps`` and
``--gate-settings`` (the gate's own 512 steps with patience; minutes per patient).

Usage:
    python scripts/amplification_probe.py                         # fresh model, machinery
    python scripts/amplification_probe.py --authority 0.3         # fresh, heads live
    python scripts/amplification_probe.py MODEL.pt --patients 12 --gate-settings --json amp.json
    python scripts/amplification_probe.py MODEL.pt --dataset BENCH.json --source cgm_real \\
        --sets glucose --max-episodes 14 --gate-settings --no-synthetic
"""

from __future__ import annotations

import argparse
import json
import math
import os
import re
import sys
import tempfile
import time
from collections import Counter
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Iterable, Sequence

_ROOT = Path(__file__).resolve().parents[1]
if str(_ROOT) not in sys.path:
    sys.path.insert(0, str(_ROOT))

import numpy as np
import torch

import pulse
from pulse.benchmark import BenchmarkEpisode, load_benchmark_dataset, sigma_obs_for, subject_of
from pulse.calibration import CalibrationSettings, MeasurementPoint, calibrate_embedding
from pulse.model import ModularPhysiologyNetwork, integrate
from pulse.modules.gut import MealEvent
from pulse.types import (
    MARKER_IDS, MARKER_INDEX, MARKERS, NORM_CENTER, NORM_SCALE, PHYSIOLOGICAL_MAX, PHYSIOLOGICAL_MIN,
)

# Guard against a scratchpad copy of `pulse` shadowing the repo (see iter96_dawn_probe.py).
assert Path(pulse.__file__).resolve().is_relative_to(_ROOT), f"shadowed pulse: {pulse.__file__}"

# The brief's pairing: glucose alone, then glucose + hr.
DEFAULT_SETS: tuple[tuple[str, ...], ...] = (("glucose",), ("glucose", "hr"))
# Disjoint from every A above, one marker per remaining module family: metabolic
# (insulin), stress (cortisol), appetite (ghrelin), cardiovascular (sbp), thermoreg (temp).
DEFAULT_HELD_OUT: tuple[str, ...] = ("insulin", "cortisol", "ghrelin", "sbp", "temp")
# A held-out marker whose prior-mean MAE is under this fraction of its NORM_SCALE has
# nothing to amplify (exactly-flat markers read 0.0; float noise on sbp is ~1e-5 mmHg).
FLAT_REL = 1e-4
# "Clearly positive" for the in-sample control. Synthetic, noise-free, zero model
# error: a calibration that has fit its own data should beat the prior mean by well
# more than this. Below it the harness (or an embedding-blind model) is the story.
CONTROL_MIN_SKILL = 0.10
# A percentile interval over resampled patients is not worth printing for a handful of
# patients (3 give ten distinct bootstrap means); below this it is left out, not faked.
MIN_UNITS_FOR_INTERVAL = 6
# |mean skill| under this reads as "no effect": 2% of the baseline error is well inside what 16
# Adam steps on a handful of patients can resolve (the six seed x set headlines of an untrained
# model span -0.14 to +0.16).
DEAD_BAND = 0.02

SPAN_CHECKIN, SPAN_WINDOW, SPAN_AHEAD = "checkin", "window", "ahead"
SPANS_SCORED = (SPAN_WINDOW, SPAN_AHEAD)
# Where the transfer comes from (see ``channel_trajectories``). Not additive.
CHANNELS = ("full", "own", "coupling", "gut")
CHANNEL_HELP = {
    "full": "every module sees the calibrated embedding (= the table above)",
    "own": "only the held-out marker's OWN module does: the shared embedding acting on B directly",
    "coupling": "only A's modules do: B moves through the coupling edges from A's changed trajectory alone",
    "gut": "only the gut kernel does: the shared meal driver every module reads",
}
# Largest |channel 'full' rollout - plain calibrated rollout| (in NORM_SCALE units) for which
# rerouting the per-module projections is trusted to reach every use of the embedding.
HOOK_TOL = 1e-4

# Output layers of the per-person heads: every ``<something>_net.<i>.weight`` (metabolic Gb /
# Ib / mass / FFA / mito / insulin-sensitivity heads, appetite Ib, stress cortisol, the
# cvs/thermo/resp setpoints, ...), zero-initialised in a fresh model. NOT the learned-dynamics
# MLPs (``network.<i>.weight``) and NOT ``default_inputs_net`` (the sleep/activity defaults,
# which this probe keeps out of the picture by passing explicit inputs). Matching on the
# suffix, not on a list of head names, is what lets a head added later come alive too.
_PERSON_HEAD = re.compile(r"(?:^|\.)(?!default_inputs_net)\w+_net\.\d+\.weight$")


# ------------------------------------------------------------------ the metric itself


def amplification_skill(mae_calibrated: float, mae_prior_mean: float) -> float:
    """``1 - MAE_calibrated / MAE_prior_mean``.

    0 exactly when calibration left the held-out prediction where the prior mean
    had it (a rejected window, or an embedding equal to the prior mean); negative
    when fitting the calibrated markers made this one worse; NaN when the baseline
    is exactly 0 (nothing to improve on).
    """
    if not mae_prior_mean > 0.0:
        return float("nan")
    return 1.0 - mae_calibrated / mae_prior_mean


def gate_skill(mae_calibrated: float, mae_prior_mean: float, sigma_obs: float) -> float:
    """benchmark.py's ``1 - MAE / max(baseline_MAE, sigma_obs)`` with the PRIOR-MEAN
    prediction as the baseline (the gate's is persistence). Not 0 for an unchanged
    embedding when the baseline is under sigma_obs: ``1 - MAE/sigma_obs`` > 0."""
    return 1.0 - mae_calibrated / max(mae_prior_mean, sigma_obs)


def is_flat(mae_prior_mean: float, marker_id: str) -> bool:
    return not mae_prior_mean >= FLAT_REL * NORM_SCALE[MARKER_INDEX[marker_id]]


def module_of(marker_id: str) -> str:
    """The module a marker belongs to (``System`` value: metabolic, appetite, stress, ...)."""
    return MARKERS[MARKER_INDEX[marker_id]].system.value


_MODULE_TAG = {"metabolic": "met", "appetite": "app", "stress": "str", "cardiovascular": "cvs",
               "thermoreg": "thm", "respiratory": "rsp", "hepatobiliary": "hpb"}


def is_cross_module(marker_id: str, calibrated: Sequence[str]) -> bool:
    """True when no calibrated marker lives in this marker's module -- the PRD's claim is
    about COUPLED modules, so insulin after a glucose calibration is the weaker case
    (same module) and cortisol, ghrelin, sbp, temp the real one."""
    return module_of(marker_id) not in {module_of(a) for a in calibrated}


def held_out_markers(
    calibrated: Sequence[str], requested: Sequence[str],
) -> tuple[list[str], list[str]]:
    """``(held_out, dropped)``: ``requested`` minus ``calibrated``, order kept.

    The held-out set is disjoint from the calibrated one by construction, so asking
    for ``glucose`` as a held-out marker of a glucose calibration cannot leak it
    back in; it is dropped and reported. Unknown ids are an error, not a skip.
    """
    unknown = [m for m in (*calibrated, *requested) if m not in MARKER_INDEX]
    if unknown:
        raise ValueError(f"unknown marker id(s): {sorted(set(unknown))}")
    cal = set(calibrated)
    kept: list[str] = []
    for m in requested:
        if m not in cal and m not in kept:
            kept.append(m)
    return kept, [m for m in requested if m in cal]


# ------------------------------------------------------------------ tallies and units


@dataclass
class Tally:
    """Sums of |error| over the scored points of one (marker, span) in one unit."""
    n: int = 0
    cal: float = 0.0       # calibrated embedding
    prior: float = 0.0     # prior-mean embedding (no calibration)
    init: float = 0.0      # the initial state carried forward (persistence)

    def add(self, truth: np.ndarray, cal: np.ndarray, prior: np.ndarray, init: float) -> None:
        self.n += int(truth.shape[0])
        self.cal += float(np.abs(cal - truth).sum())
        self.prior += float(np.abs(prior - truth).sum())
        self.init += float(np.abs(init - truth).sum())


@dataclass
class UnitScore:
    """One synthetic patient or one real episode, under one calibrated set A."""
    unit: str
    subject: str
    accepted: bool
    reason: str
    steps: int
    cells: dict[tuple[str, str], Tally] = field(default_factory=dict)
    emb_dist_prior: float = float("nan")   # ||e_prior - e_true||, synthetic only
    emb_dist_cal: float = float("nan")     # ||e_calibrated - e_true||, synthetic only
    emb_norm: float = float("nan")
    diverged: bool = False
    seconds: float = 0.0
    channels: dict[tuple[str, str], Tally] = field(default_factory=dict)   # (channel, marker)
    hook_err: float = float("nan")     # max |rerouted full rollout - plain calibrated rollout| / NORM_SCALE

    def cell(self, marker: str, span: str) -> Tally:
        return self.cells.setdefault((marker, span), Tally())

    def mae(self, marker: str, spans: Iterable[str]) -> tuple[float, float, float, int] | None:
        """``(MAE_cal, MAE_prior, MAE_init, n)`` over ``spans``, or None without points."""
        n = sum(self.cells[(marker, s)].n for s in spans if (marker, s) in self.cells)
        if n == 0:
            return None
        parts = [self.cells[(marker, s)] for s in spans if (marker, s) in self.cells]
        return (sum(p.cal for p in parts) / n, sum(p.prior for p in parts) / n,
                sum(p.init for p in parts) / n, n)


@dataclass
class Row:
    marker: str
    role: str                  # "fit pts" | "calibrated" (A) | "cross" | "same" (held-out)
    n_points: int
    n_units: int
    mae_cal: float
    mae_prior: float
    mae_init: float
    skill: float
    skill_gate: float
    floor_active: bool         # prior-mean MAE under sigma_obs: the gate would floor it
    flat: bool
    improved: int
    worse: int
    tied: int
    skill_window: float = float("nan")
    skill_ahead: float = float("nan")

    @property
    def held_out(self) -> bool:
        return self.role in ("cross", "same")


def summarize(
    units: Sequence[UnitScore], marker: str, spans: Sequence[str], role: str,
) -> Row | None:
    """Episode-first (here: patient-first) pooled row for one marker, as the gate does:
    per-unit MAE, mean over units, then the ratio."""
    per = [(u, u.mae(marker, spans)) for u in units]
    per = [(u, m) for u, m in per if m is not None]
    if not per:
        return None
    cal = float(np.mean([m[0] for _, m in per]))
    prior = float(np.mean([m[1] for _, m in per]))
    init = float(np.mean([m[2] for _, m in per]))
    improved = worse = tied = 0
    for _, (c, p, _i, _n) in per:
        if math.isclose(c, p, rel_tol=1e-9, abs_tol=0.0):
            tied += 1
        elif c < p:
            improved += 1
        else:
            worse += 1
    sigma = sigma_obs_for(marker)

    def _span_skill(sp: str) -> float:
        s = [u.mae(marker, (sp,)) for u in units]
        s = [m for m in s if m is not None]
        if not s:
            return float("nan")
        return amplification_skill(float(np.mean([m[0] for m in s])), float(np.mean([m[1] for m in s])))

    return Row(
        marker=marker, role=role, n_points=sum(m[3] for _, m in per), n_units=len(per),
        mae_cal=cal, mae_prior=prior, mae_init=init,
        skill=amplification_skill(cal, prior), skill_gate=gate_skill(cal, prior, sigma),
        floor_active=prior < sigma, flat=is_flat(prior, marker),
        improved=improved, worse=worse, tied=tied,
        skill_window=_span_skill(SPAN_WINDOW), skill_ahead=_span_skill(SPAN_AHEAD),
    )


def per_unit_mae_matrix(
    units: Sequence[UnitScore], markers: Sequence[str], spans: Sequence[str],
) -> tuple[np.ndarray, np.ndarray]:
    """``[units, markers]`` MAEs (calibrated, prior mean); NaN where a unit has no points."""
    cal = np.full((len(units), len(markers)), np.nan)
    pri = np.full((len(units), len(markers)), np.nan)
    for i, u in enumerate(units):
        for j, m in enumerate(markers):
            r = u.mae(m, spans)
            if r is not None:
                cal[i, j], pri[i, j] = r[0], r[1]
    return cal, pri


def headline_skill(cal: np.ndarray, pri: np.ndarray, markers: Sequence[str]) -> dict[str, Any]:
    """Mean (and median) over non-flat held-out markers of the pooled per-marker skill."""
    skills: dict[str, float] = {}
    n_flat = 0
    for j, m in enumerate(markers):
        ok = ~np.isnan(pri[:, j])
        if not ok.any():
            continue
        c, p = float(np.mean(cal[ok, j])), float(np.mean(pri[ok, j]))
        if is_flat(p, m):
            n_flat += 1
            continue
        skills[m] = amplification_skill(c, p)
    vals = [v for v in skills.values() if not math.isnan(v)]
    return {
        "mean": float(np.mean(vals)) if vals else float("nan"),
        "median": float(np.median(vals)) if vals else float("nan"),
        "n_markers": len(vals), "n_flat": n_flat, "per_marker": skills,
    }


def bootstrap_headline(
    cal: np.ndarray, pri: np.ndarray, markers: Sequence[str], *,
    n_boot: int = 1000, seed: int = 0, lo: float = 5.0, hi: float = 95.0,
) -> tuple[float, float] | None:
    """Percentile interval of the headline over resampled PATIENTS (the unit of
    independence; the scored minutes inside one patient are not). None below
    ``MIN_UNITS_FOR_INTERVAL`` units."""
    u = cal.shape[0]
    if u < MIN_UNITS_FOR_INTERVAL:
        return None
    rng = np.random.default_rng(seed)
    out = []
    for _ in range(n_boot):
        idx = rng.integers(0, u, size=u)
        h = headline_skill(cal[idx], pri[idx], markers)["mean"]
        if not math.isnan(h):
            out.append(h)
    if len(out) < n_boot // 2:
        return None
    return float(np.percentile(out, lo)), float(np.percentile(out, hi))


# ------------------------------------------------------------------ models


def freeze(model: ModularPhysiologyNetwork) -> ModularPhysiologyNetwork:
    """Eval mode, no parameter grads: calibration steps ``[embedding]`` only (see
    benchmark._benchmark_worker_init)."""
    model.eval()
    for p in model.parameters():
        p.requires_grad_(False)
    return model


def give_embedding_authority(model: ModularPhysiologyNetwork, std: float, seed: int) -> int:
    """Re-draw every ALL-ZERO per-person head output matrix from ``N(0, std^2)``.

    A fresh model's per-person heads (Gb, Ib, body mass, FFA_b, mito, cortisol_b and
    the cvs/thermo/resp setpoints) end in zero-initialised matrices, so "every
    embedding is the median person" and the embedding reaches the trajectory only
    through the gut kernel. This gives the heads something to say so the full path
    can be exercised; it is a MACHINERY switch, not a trained model. Returns the
    number of matrices touched (0 means the head names changed: look at the model).
    """
    g = torch.Generator().manual_seed(seed)
    n = 0
    with torch.no_grad():
        for name, p in model.named_parameters():
            if p.ndim == 2 and _PERSON_HEAD.search(name) and bool((p == 0).all()):
                p.copy_(torch.randn(p.shape, generator=g) * std)
                n += 1
    return n


def fresh_model(seed: int = 0, authority: float = 0.0, **kwargs: Any) -> ModularPhysiologyNetwork:
    torch.manual_seed(seed)
    model = ModularPhysiologyNetwork(**kwargs)
    if authority > 0.0:
        give_embedding_authority(model, authority, seed + 2)
    return freeze(model)


def load_model(path: str) -> tuple[ModularPhysiologyNetwork, dict[str, Any]]:
    """Load a checkpoint the way scripts/rescore_artifact.py does (local path or gs://);
    ``from_checkpoint`` attaches the trained prior as ``_embedding_prior_{mean,std}``."""
    if path.startswith("gs://"):
        from pulse.train import _download_gs_uri_to_file  # lazy: pulls in the trainer
        fd, local = tempfile.mkstemp(suffix=".pt")
        os.close(fd)
        print(f"downloading {path} ...", flush=True)
        _download_gs_uri_to_file(path, local)
        path = local
    blob = torch.load(path, map_location="cpu", weights_only=False)
    return freeze(ModularPhysiologyNetwork.from_checkpoint(blob)), blob


def prior_stats(model: ModularPhysiologyNetwork) -> tuple[torch.Tensor | None, torch.Tensor | None]:
    pm = getattr(model, "_embedding_prior_mean", None)
    ps = getattr(model, "_embedding_prior_std", None)
    return (pm, ps) if pm is not None and ps is not None else (None, None)


def prior_embedding(model: ModularPhysiologyNetwork) -> torch.Tensor:
    """The no-calibration embedding: the trained prior mean, else zeros (what
    ``calibrate_embedding`` itself starts from)."""
    pm, _ = prior_stats(model)
    return pm.detach().clone().float() if pm is not None else torch.zeros(model.embedding_dim)


# ------------------------------------------------------------------ synthetic patients


@dataclass(frozen=True)
class Protocol:
    """One short synthetic day. A is observed over ``(0, cal_end_min]`` every
    ``obs_every_min``; everything is scored every ``score_every_min`` over
    ``(0, duration_min)`` -- split into ``window`` (<= cal_end) and ``ahead``."""
    duration_min: int = 120
    cal_end_min: int = 60
    obs_every_min: int = 10
    score_every_min: int = 5
    start_time_minutes: float = 420.0
    meal_at_min: float | None = 10.0       # None / negative: fasting
    meal_carbs_g: float = 60.0
    meal_fats_g: float = 10.0
    meal_proteins_g: float = 15.0
    # Explicit external inputs for every minute (awake, at rest). With them the only way the
    # embedding reaches the dynamics is the per-module projections, as in the gate's masked
    # episodes; with None the model substitutes defaults that READ the embedding directly.
    sleep_wake: float = 1.0
    activity: float = 0.0

    def __post_init__(self) -> None:
        if not 0 < self.cal_end_min < self.duration_min:
            raise ValueError("need 0 < cal_end_min < duration_min")
        if len(self.obs_times()) < 3:
            raise ValueError("need >= 3 check-in times (calibration holds the last ~20% out)")

    def masks(self) -> tuple[torch.Tensor, torch.Tensor]:
        return (torch.full((self.duration_min,), float(self.sleep_wake)),
                torch.full((self.duration_min,), float(self.activity)))

    def meals(self) -> list[MealEvent]:
        if self.meal_at_min is None or self.meal_at_min < 0:
            return []
        return [MealEvent(time=float(self.meal_at_min), carbs=self.meal_carbs_g,
                          fats=self.meal_fats_g, proteins=self.meal_proteins_g)]

    def obs_times(self) -> list[int]:
        return list(range(self.obs_every_min, self.cal_end_min + 1, self.obs_every_min))

    def score_times(self) -> list[int]:
        return list(range(self.score_every_min, self.duration_min, self.score_every_min))

    def span_times(self) -> dict[str, list[int]]:
        st = self.score_times()
        return {SPAN_CHECKIN: self.obs_times(),
                SPAN_WINDOW: [t for t in st if t <= self.cal_end_min],
                SPAN_AHEAD: [t for t in st if t > self.cal_end_min]}


@dataclass
class Patient:
    index: int
    embedding: torch.Tensor        # the true embedding
    initial_state: torch.Tensor
    truth: torch.Tensor            # [duration, STATE_DIM], the model's own trajectory


def draw_embeddings(
    model: ModularPhysiologyNetwork, n: int, *, seed: int, emb_sd: float = 0.1,
    scale: float = 1.0, table: torch.Tensor | None = None,
) -> list[torch.Tensor]:
    """``n`` true embeddings: rows of the trained table if given, else
    ``prior_mean + scale * prior_std * z`` when the model carries a prior, else
    ``N(0, emb_sd^2)``. One generator, drawn per patient, so patient i is the same
    patient whatever ``n`` is."""
    g = torch.Generator().manual_seed(seed)
    pm, ps = prior_stats(model)
    out = []
    for i in range(n):
        z = torch.randn(model.embedding_dim, generator=g)
        if table is not None:
            out.append(table[i % table.shape[0]].detach().clone().float())
        elif pm is not None:
            out.append((pm + scale * ps * z).float())
        else:
            out.append((emb_sd * z).float())
    return out


def person_initial_state(
    model: ModularPhysiologyNetwork, embedding: torch.Tensor,
) -> tuple[torch.Tensor, bool]:
    """NORM_CENTER with glucose / hr / hrv / sbp / dbp at THIS person's setpoints, decoded by
    the modules themselves (A1 moved them to log space; iter89_recovery_test.py does the
    same). ``(state, ok)``: not ok means a decoder is gone and the typical state came back."""
    st = torch.tensor(NORM_CENTER, dtype=torch.float32)
    try:
        with torch.no_grad():
            e_met = model.embedding_projections["metabolic"](embedding)
            e_cvs = model.embedding_projections["cardiovascular"](embedding)
            gb = float(model.metabolic.glucose_setpoint_raw(e_met))
            hr, hrv, sbp, dbp = (float(x) for x in model.cardiovascular.setpoints_raw(e_cvs))
    except (AttributeError, KeyError, TypeError, ValueError):
        return st, False
    for marker, v in (("glucose", gb), ("hr", hr), ("hrv", hrv), ("sbp", sbp), ("dbp", dbp)):
        st[MARKER_INDEX[marker]] = v
    return st, True


def rollout(
    model: ModularPhysiologyNetwork, state: torch.Tensor, embedding: torch.Tensor, protocol: Protocol,
) -> torch.Tensor:
    sw, act = protocol.masks()
    with torch.no_grad():
        return integrate(
            model=model, initial_state=state, embedding=embedding, n_steps=protocol.duration_min,
            dt=1.0, start_time_minutes=protocol.start_time_minutes, meals=protocol.meals(),
            sleep_wake=sw, activity=act,
        )


def make_patient(
    model: ModularPhysiologyNetwork, index: int, embedding: torch.Tensor, protocol: Protocol,
    init: str = "person",
) -> tuple[Patient, bool]:
    """A synthetic patient and whether the person-specific initial state was available."""
    ok = True
    if init == "person":
        state, ok = person_initial_state(model, embedding)
    else:
        state = torch.tensor(NORM_CENTER, dtype=torch.float32)
    return Patient(index, embedding, state, rollout(model, state, embedding, protocol)), ok


def _finite_or_clipped(traj: torch.Tensor) -> tuple[torch.Tensor, bool]:
    """A calibrated embedding that detonates the forward pass is the worst possible
    held-out result, not a missing one: score it at the physiological envelope."""
    if bool(torch.isfinite(traj).all()):
        return traj, False
    lo = torch.tensor(PHYSIOLOGICAL_MIN, dtype=traj.dtype)
    hi = torch.tensor(PHYSIOLOGICAL_MAX, dtype=traj.dtype)
    traj = torch.nan_to_num(traj, nan=0.0, posinf=1e30, neginf=-1e30)
    return torch.max(torch.min(traj, hi), lo), True


@contextmanager
def seen_by(model: ModularPhysiologyNetwork, override: dict[str, torch.Tensor]):
    """Inside the block, the projection of each module in ``override`` reads that embedding
    instead of the one ``integrate`` was given. The model projects the embedding per module
    with ``proj(embedding)`` (forward, the rollout plan, the gut precompute), so a pre-hook
    on the projection reroutes exactly that read and nothing else."""
    handles = []
    try:
        for name, emb in override.items():
            def pre(_module, args, emb=emb):
                x = args[0]
                return (emb.to(x.dtype).expand_as(x), *args[1:])
            handles.append(model.embedding_projections[name].register_forward_pre_hook(pre))
        yield
    finally:
        for h in handles:
            h.remove()


def channel_trajectories(
    model: ModularPhysiologyNetwork, roll: Any, e_prior: torch.Tensor, e_cal: torch.Tensor,
    a_markers: Sequence[str], b_markers: Sequence[str],
) -> dict[str, Any]:
    """Held-out trajectories when only PART of the model sees the calibrated embedding.

    Calibration moves one shared vector, and "a glucose reading constrains ghrelin" can be
    true for two different reasons: (1) the coupling graph -- A's module is now different, B
    reads A's output; (2) the shared embedding -- B's own parameters moved with the code, or
    both read the same upstream driver (the gut kernel). The table reports the sum. Here the
    rollout is run with the prior-mean embedding everywhere EXCEPT:

    * ``coupling``: A's modules       -> B can move only through coupling edges;
    * ``own[module]``: B's own module -> B moves only through its own parameters;
    * ``gut``: the gut kernel         -> only the shared meal driver moves;
    * ``every``: all of them          -> must equal the plain calibrated rollout.

    ``roll(embedding) -> [T, STATE_DIM]`` is the unit's own no-grad rollout.
    """
    names = list(model.embedding_projections)
    a_mods = {module_of(a) for a in a_markers} & set(names)
    out: dict[str, Any] = {"own": {}}
    with seen_by(model, {n: e_cal for n in names}):
        out["every"] = roll(e_prior)
    with seen_by(model, {n: e_cal for n in a_mods}):
        out["coupling"] = roll(e_prior)
    with seen_by(model, {"gut": e_cal}):
        out["gut"] = roll(e_prior)
    for mod in sorted({module_of(b) for b in b_markers} & set(names)):
        with seen_by(model, {mod: e_cal}):
            out["own"][mod] = roll(e_prior)
    return out


def tally_channels(
    unit: "UnitScore", model: ModularPhysiologyNetwork, roll: Any, e_prior: torch.Tensor,
    e_cal: torch.Tensor, pred_cal: torch.Tensor, pred_prior: torch.Tensor,
    a_markers: Sequence[str], targets: dict[str, tuple[list[int], np.ndarray]],
    initial_state: torch.Tensor,
) -> None:
    """Fill ``unit.channels[(channel, marker)]``; ``targets[marker] = (times, truth)`` are the
    held-out points to score (the dense grid for a synthetic patient, the measured points of a
    real episode)."""
    targets = {mk: tv for mk, tv in targets.items() if len(tv[0])}
    if not targets:
        return
    if torch.equal(e_cal, e_prior):          # rejected: every channel IS the prior
        ch = {"every": pred_prior, "coupling": pred_prior, "gut": pred_prior,
              "own": {module_of(b): pred_prior for b in targets}}
        unit.hook_err = 0.0
    else:
        ch = channel_trajectories(model, roll, e_prior, e_cal, a_markers, list(targets))
        scale = torch.tensor(NORM_SCALE, dtype=pred_cal.dtype)
        unit.hook_err = float(((ch["every"] - pred_cal).abs() / scale).max())
    for mk, (times, truth) in targets.items():
        j = MARKER_INDEX[mk]
        pri = pred_prior[times, j].numpy().astype(np.float64)
        trajs = {"full": pred_cal, "coupling": ch["coupling"], "gut": ch["gut"],
                 "own": ch["own"].get(module_of(mk), pred_prior)}
        for name, traj in trajs.items():
            unit.channels.setdefault((name, mk), Tally()).add(
                truth, traj[times, j].numpy().astype(np.float64), pri, float(initial_state[j]))


def score_patient(
    model: ModularPhysiologyNetwork, patient: Patient, protocol: Protocol,
    a_markers: Sequence[str], b_markers: Sequence[str], *,
    e_prior: torch.Tensor, settings: CalibrationSettings, obs_noise: float = 0.0,
    noise_seed: int = 0, channels: bool = True,
) -> UnitScore:
    """Calibrate on ``a_markers`` only, then score A (control) and ``b_markers``."""
    if set(a_markers) & set(b_markers):
        raise ValueError(f"held-out markers overlap the calibrated set: {set(a_markers) & set(b_markers)}")
    g = torch.Generator().manual_seed(noise_seed + 7919 * patient.index)
    obs = []
    for mk in a_markers:
        for t in protocol.obs_times():
            v = float(patient.truth[t, MARKER_INDEX[mk]])
            if obs_noise > 0.0:
                v += obs_noise * sigma_obs_for(mk) * float(torch.randn((), generator=g))
            obs.append(MeasurementPoint(time=t, marker_id=mk, value=v))
    # The held-out set never reaches calibration: only A's markers are observed.
    assert {o.marker_id for o in obs} == set(a_markers)

    pm, ps = prior_stats(model)
    sw, act = protocol.masks()
    t_start = time.time()
    res = calibrate_embedding(
        model, obs, patient.initial_state, protocol.meals(), protocol.duration_min,
        start_time_minutes=protocol.start_time_minutes, sleep_wake=sw, activity=act,
        prior_mean=pm, prior_std=ps, settings=settings,
    )
    pred_prior = rollout(model, patient.initial_state, e_prior, protocol)
    same = torch.equal(res.embedding, e_prior)
    pred_cal, diverged = (pred_prior, False) if same else _finite_or_clipped(
        rollout(model, patient.initial_state, res.embedding, protocol))

    unit = UnitScore(
        unit=f"synthetic-{patient.index:02d}", subject=f"synthetic-{patient.index:02d}",
        accepted=bool(res.accepted), reason=res.reason, steps=int(res.n_steps),
        emb_dist_prior=float((e_prior - patient.embedding).norm()),
        emb_dist_cal=float((res.embedding - patient.embedding).norm()),
        emb_norm=float(res.embedding.norm()), diverged=diverged,
    )
    for mk in (*a_markers, *b_markers):
        j = MARKER_INDEX[mk]
        truth = patient.truth[:, j].numpy().astype(np.float64)
        cal = pred_cal[:, j].numpy().astype(np.float64)
        pri = pred_prior[:, j].numpy().astype(np.float64)
        init = float(patient.initial_state[j])
        for span, times in protocol.span_times().items():
            if span == SPAN_CHECKIN and mk not in a_markers:
                continue
            if times:
                unit.cell(mk, span).add(truth[times], cal[times], pri[times], init)
    if channels:
        grid = protocol.score_times()
        tally_channels(
            unit, model, lambda e: rollout(model, patient.initial_state, e, protocol), e_prior,
            res.embedding, pred_cal, pred_prior, a_markers,
            {mk: (grid, patient.truth[grid, MARKER_INDEX[mk]].numpy().astype(np.float64)) for mk in b_markers},
            patient.initial_state)
    unit.seconds = time.time() - t_start
    return unit


# ------------------------------------------------------------------ real episodes


def _episode_points(ep: BenchmarkEpisode) -> tuple[list[MeasurementPoint], list[MeasurementPoint]]:
    """``(check_in_points, eval_points)``: every numeric marker in the episode's
    calibration check-ins and in its eval measurements (not just the gate's five)."""
    checkins: list[MeasurementPoint] = []
    for c in ep.calibration_check_ins:
        if not isinstance(c, dict) or c.get("time") is None:
            continue
        t = int(round(float(c["time"])))
        if not 0 <= t < ep.duration_min:
            continue
        for mk, v in (c.get("measurements") or {}).items():
            if mk in MARKER_INDEX and isinstance(v, (int, float)) and not isinstance(v, bool):
                checkins.append(MeasurementPoint(time=t, marker_id=mk, value=float(v)))
    return checkins, [p for p in ep.eval_measurements if p.marker_id in MARKER_INDEX]


def episode_markers(episodes: Sequence[BenchmarkEpisode]) -> list[str]:
    """Markers with any measurement in these episodes, in canonical order."""
    seen: set[str] = set()
    for ep in episodes:
        ci, ev = _episode_points(ep)
        seen.update(p.marker_id for p in (*ci, *ev))
    return [m for m in MARKER_IDS if m in seen]


def score_episode(
    model: ModularPhysiologyNetwork, ep: BenchmarkEpisode, a_markers: Sequence[str],
    b_markers: Sequence[str], *, e_prior: torch.Tensor, settings: CalibrationSettings,
    channels: bool = True,
) -> UnitScore | None:
    """Calibrate on A's check-ins (the gate's inputs: start time, masks, prior), score the
    rest. None when the episode has no check-in of any A marker."""
    checkins, evals = _episode_points(ep)
    a_obs = [p for p in checkins if p.marker_id in a_markers]
    if len({p.time for p in a_obs}) < 2:
        return None
    t0 = float(ep.start_time_minutes) % 1440.0 if ep.start_time_minutes is not None else 360.0
    init = torch.tensor(ep.initial_state, dtype=torch.float32)
    sw = None if ep.sleep_wake is None else torch.tensor(ep.sleep_wake[:ep.duration_min], dtype=torch.float32)
    act = None if ep.activity is None else torch.tensor(ep.activity[:ep.duration_min], dtype=torch.float32)

    pm, ps = prior_stats(model)
    t_start = time.time()
    res = calibrate_embedding(
        model, a_obs, init, ep.meals, ep.duration_min, start_time_minutes=t0,
        sleep_wake=sw, activity=act, prior_mean=pm, prior_std=ps, settings=settings,
    )

    def _roll(emb: torch.Tensor) -> torch.Tensor:
        with torch.no_grad():
            return integrate(model=model, initial_state=init, embedding=emb, n_steps=ep.duration_min,
                             dt=1.0, start_time_minutes=t0, meals=ep.meals, sleep_wake=sw, activity=act)

    pred_prior = _roll(e_prior)
    same = torch.equal(res.embedding, e_prior)
    pred_cal, diverged = (pred_prior, False) if same else _finite_or_clipped(_roll(res.embedding))

    unit = UnitScore(
        unit=ep.user_id, subject=subject_of(ep.user_id), accepted=bool(res.accepted),
        reason=res.reason, steps=int(res.n_steps), emb_norm=float(res.embedding.norm()),
        diverged=diverged,
    )
    wanted = set(a_markers) | set(b_markers)
    # A's check-ins are the in-sample control; B's check-ins (never fed to calibration)
    # are the in-window held-out points; everything in eval is later than calibration.
    for span, pts in ((SPAN_CHECKIN, [p for p in checkins if p.marker_id in a_markers]),
                      (SPAN_WINDOW, [p for p in checkins if p.marker_id in b_markers]),
                      (SPAN_AHEAD, [p for p in evals if p.marker_id in wanted])):
        for mk in {p.marker_id for p in pts}:
            sel = [p for p in pts if p.marker_id == mk]
            j = MARKER_INDEX[mk]
            ts = [p.time for p in sel]
            truth = np.array([p.value for p in sel], dtype=np.float64)
            unit.cell(mk, span).add(
                truth, pred_cal[ts, j].numpy().astype(np.float64),
                pred_prior[ts, j].numpy().astype(np.float64), float(ep.initial_state[j]))
    if channels:
        targets = {}
        for mk in b_markers:
            sel = [q for q in (*checkins, *evals) if q.marker_id == mk]
            if sel:
                targets[mk] = ([p.time for p in sel], np.array([p.value for p in sel], dtype=np.float64))
        tally_channels(unit, model, _roll, e_prior, res.embedding, pred_cal, pred_prior, a_markers,
                       targets, init)
    unit.seconds = time.time() - t_start
    return unit


# ------------------------------------------------------------------ reporting


@dataclass
class SetResult:
    source: str                         # "synthetic" | "real"
    a_markers: list[str]
    b_markers: list[str]
    dropped: list[str]
    units: list[UnitScore]
    rows: list[Row]
    headline: dict[str, Any]            # every non-flat held-out marker
    headline_cross: dict[str, Any]      # ... in a module none of A belongs to (the PRD's claim)
    headline_same: dict[str, Any]       # ... in an A marker's own module
    headline_accepted: dict[str, Any]   # ... over accepted windows only
    interval: tuple[float, float] | None
    interval_cross: tuple[float, float] | None
    control_checkin: float
    control_ok: bool
    control_text: str
    channel_skill: dict[str, dict[str, float]] = field(default_factory=dict)   # channel -> marker -> skill
    channel_cross: dict[str, float] = field(default_factory=dict)              # channel -> mean over x-module
    hook_err: float = float("nan")

    @property
    def accepted(self) -> int:
        return sum(u.accepted for u in self.units)


_NO_HEADLINE = {"mean": float("nan"), "median": float("nan"), "n_markers": 0, "n_flat": 0, "per_marker": {}}


def build_set_result(
    source: str, units: Sequence[UnitScore], a_markers: Sequence[str],
    b_markers: Sequence[str], dropped: Sequence[str] = (),
) -> SetResult:
    rows: list[Row] = []
    for mk in a_markers:
        for role, spans in (("fit pts", (SPAN_CHECKIN,)), ("calibrated", SPANS_SCORED)):
            r = summarize(units, mk, spans, role)
            if r is not None:
                rows.append(r)
    held = []
    for mk in b_markers:
        r = summarize(units, mk, SPANS_SCORED, "cross" if is_cross_module(mk, a_markers) else "same")
        if r is not None:
            held.append(r)
    rows.extend(held)

    markers = [r.marker for r in held]
    cross = [r.marker for r in held if r.role == "cross"]
    same = [r.marker for r in held if r.role == "same"]
    cal, pri = per_unit_mae_matrix(units, markers, SPANS_SCORED)
    head = headline_skill(cal, pri, markers) if markers else dict(_NO_HEADLINE)
    ccal, cpri = per_unit_mae_matrix(units, cross, SPANS_SCORED)
    head_cross = headline_skill(ccal, cpri, cross) if cross else dict(_NO_HEADLINE)
    scal, spri = per_unit_mae_matrix(units, same, SPANS_SCORED)
    head_same = headline_skill(scal, spri, same) if same else dict(_NO_HEADLINE)
    acc_units = [u for u in units if u.accepted]
    acal, apri = per_unit_mae_matrix(acc_units, markers, SPANS_SCORED)
    head_acc = headline_skill(acal, apri, markers) if acc_units and markers else dict(_NO_HEADLINE)
    interval = bootstrap_headline(cal, pri, markers) if markers else None
    interval_cross = bootstrap_headline(ccal, cpri, cross) if cross else None

    fit = [r for r in rows if r.role == "fit pts" and not r.flat]
    control = float(np.mean([r.skill for r in fit])) if fit else float("nan")
    acc = sum(u.accepted for u in units)
    if acc == 0:
        ok, text = False, ("CONTROL UNINFORMATIVE: no window was accepted, so the embedding never moved and "
                           "every skill is 0 by construction. Expected on an embedding-blind model (a fresh "
                           "model's per-person heads are zero-initialised: try --authority 0.3), or when the "
                           "A window carries no evidence the hold-out can confirm.")
    elif not fit:
        ok, text = False, "CONTROL UNINFORMATIVE: every calibrated marker is flat on this model."
    elif control < CONTROL_MIN_SKILL:
        ok, text = False, (f"CONTROL FAILED: in-sample skill on the calibrated markers is {control:+.2f} "
                           f"(< {CONTROL_MIN_SKILL:.2f}). Calibration did not even fit its own data, so the "
                           "held-out numbers above are not evidence about coupling: fix this first.")
    else:
        ok, text = True, (f"control ok: in-sample skill on the calibrated markers is {control:+.2f} "
                          f"(>= {CONTROL_MIN_SKILL:.2f}).")
    if source == "real":
        # On real episodes the calibrated rows hold only the eval points, i.e. the OUT-of-sample
        # control: the iter-96 sweep found calibration worse than not calibrating on glucose and hr.
        oos = [r.skill for r in rows if r.role == "calibrated" and not r.flat and not math.isnan(r.skill)]
        if oos:
            m_oos = float(np.mean(oos))
            text += (f" Out-of-sample (eval points) the calibrated markers score {m_oos:+.2f}"
                     + ("" if m_oos >= 0 else " -- calibration is WORSE than not calibrating even on the "
                        "markers it was fit to (the iter-96 sweep finding)") + ".")
    chan: dict[str, dict[str, float]] = {c: {} for c in CHANNELS}
    for c in CHANNELS:
        for r in held:
            if r.flat:
                continue
            parts = [u.channels[(c, r.marker)] for u in units if (c, r.marker) in u.channels
                     and u.channels[(c, r.marker)].n]
            if parts:
                chan[c][r.marker] = amplification_skill(
                    float(np.mean([t.cal / t.n for t in parts])), float(np.mean([t.prior / t.n for t in parts])))
    cross_live = [r.marker for r in held if r.role == "cross" and not r.flat]
    chan_cross = {c: float(np.mean([v[m] for m in cross_live if m in v])) for c, v in chan.items()
                  if any(m in v for m in cross_live)}
    errs = [u.hook_err for u in units if not math.isnan(u.hook_err)]
    return SetResult(source, list(a_markers), list(b_markers), list(dropped), list(units), rows,
                     head, head_cross, head_same, head_acc, interval, interval_cross, control, ok, text,
                     chan, chan_cross, max(errs) if errs else float("nan"))


def _g(x: float, w: int = 9) -> str:
    return f"{'-':>{w}}" if x is None or (isinstance(x, float) and math.isnan(x)) else f"{x:>{w}.3g}"


def _s(x: float, w: int = 7) -> str:
    return f"{'-':>{w}}" if x is None or (isinstance(x, float) and math.isnan(x)) else f"{x:>+{w}.2f}"


def _verdict(mean: float, interval: tuple[float, float] | None, n_units: int) -> str:
    if interval is not None and interval[0] <= 0.0 <= interval[1]:
        return (f"INDISTINGUISHABLE FROM ZERO: the 90% interval over {n_units} patients spans 0 "
                f"(point estimate {mean:+.3f})")
    text = ("POSITIVE: fitting A moved B toward the truth" if mean > DEAD_BAND else
            "NEGATIVE: fitting A made B worse (error laundered, not information carried)" if mean < -DEAD_BAND
            else f"ZERO: calibration changed nothing B could feel (|skill| < {DEAD_BAND:g})")
    return text + ("" if interval is not None or n_units < 2 else
                   f" (only {n_units} patients: no interval, read the sign as anecdote)")


def _span(iv: tuple[float, float] | None) -> str:
    return f"  [90% over patients {iv[0]:+.3f}, {iv[1]:+.3f}]" if iv else ""


def render_set(res: SetResult) -> str:
    a = "+".join(res.a_markers)
    n = len(res.units)
    reasons = Counter(u.reason for u in res.units)
    lines = [
        "",
        f"=== calibrate on {a}  [{res.source}: {n} {'patients' if res.source == 'synthetic' else 'episodes'}"
        + (f", {len({u.subject for u in res.units})} subject(s)" if res.source == "real" else "") + "] ===",
        f"calibration accepted in {res.accepted}/{n} windows "
        f"({res.accepted / max(n, 1):.0%})   reasons: " + ", ".join(f"{k} x{v}" for k, v in sorted(reasons.items())),
    ]
    if res.dropped:
        lines.append(f"(dropped from the held-out set because they are calibrated here: {', '.join(res.dropped)})")
    if any(u.diverged for u in res.units):
        lines.append(f"WARNING: {sum(u.diverged for u in res.units)} calibrated trajectories were non-finite "
                     "and are scored at the physiological envelope")
    syn = [u for u in res.units if not math.isnan(u.emb_dist_cal)]
    if syn:
        ratio = [u.emb_dist_cal / u.emb_dist_prior for u in syn if u.emb_dist_prior > 0]
        closer = sum(u.emb_dist_cal < u.emb_dist_prior for u in syn if u.accepted)
        lines.append(f"embedding distance to the true embedding: prior-mean {np.mean([u.emb_dist_prior for u in syn]):.3f}"
                     f" -> calibrated {np.mean([u.emb_dist_cal for u in syn]):.3f}"
                     f" (mean ratio {np.mean(ratio):.2f}; closer in {closer}/{res.accepted} accepted)")
    lines.append(
        f"{'marker':<9}{'mod':<4}{'role':<11}{'MAE_cal':>9}{'MAE_prior':>10}{'MAE_init':>9}{'skill':>8}{'gate':>8} "
        f"{'+/-/=':>7}{'n':>6}{'window':>8}{'ahead':>8}")
    for r in res.rows:
        init = _g(r.mae_init) if r.held_out else _g(float("nan"))
        skill = "flat".rjust(8) if r.flat else _s(r.skill, 8)
        gate = ("flat".rjust(8) if r.flat else _s(r.skill_gate, 7) + ("*" if r.floor_active else " "))
        wins = f"{r.improved}/{r.worse}/{r.tied}"
        span_cols = ("-".rjust(16) if r.flat or r.role == "fit pts"
                     else _s(r.skill_window, 8) + _s(r.skill_ahead, 8))
        lines.append(f"{r.marker:<9}{_MODULE_TAG.get(module_of(r.marker), '?'):<4}{r.role:<11}{_g(r.mae_cal)}{_g(r.mae_prior, 10)}"
                     f"{init}{skill}{gate} {wins:>7}{r.n_points:>6}{span_cols}")
    h, hc, hs, ha = res.headline, res.headline_cross, res.headline_same, res.headline_accepted
    lines.append("")
    if h["n_markers"]:
        lines.append(f"HEADLINE  calibrate on {a} -> mean skill over {h['n_markers']} held-out markers = "
                     f"{h['mean']:+.3f} (median {h['median']:+.3f}){_span(res.interval)}"
                     + (f"; {h['n_flat']} flat marker(s) excluded" if h["n_flat"] else ""))
        if hc["n_markers"] or hs["n_markers"]:
            part = []
            if hc["n_markers"]:
                part.append(f"cross-module {hc['mean']:+.3f} over {hc['n_markers']} ({', '.join(hc['per_marker'])})"
                            f"{_span(res.interval_cross)}")
            if hs["n_markers"]:
                part.append(f"same-module {hs['mean']:+.3f} over {hs['n_markers']} ({', '.join(hs['per_marker'])})")
            lines.append("          " + "; ".join(part))
        if res.accepted and res.accepted < n and ha["n_markers"]:
            lines.append(f"          accepted windows only ({res.accepted}/{n}): {ha['mean']:+.3f}")
        lines.append(f"          {_verdict(h['mean'], res.interval, n)}")
    else:
        lines.append(f"HEADLINE  calibrate on {a} -> no held-out marker has signal on this model "
                     f"({h['n_flat']} flat): nothing to amplify, skill undefined")
    lines.append(f"          {res.control_text}")
    if any(res.channel_skill.get(c) for c in CHANNELS):
        if res.hook_err > HOOK_TOL:
            lines.append(f"CHANNELS  untrusted: rerouting every module's projection to the calibrated embedding does "
                         f"not reproduce the plain calibrated rollout (max |diff|/NORM_SCALE {res.hook_err:.2g} > "
                         f"{HOOK_TOL:g}), so the model reads the embedding somewhere else too. Skipped.")
        else:
            live = [r for r in res.rows if r.held_out and not r.flat]
            lines.append("")
            lines.append("CHANNELS  skill vs prior mean when only part of the model sees the calibrated embedding "
                         "(not additive)")
            lines.append(f"{'marker':<9}{'mod':<4}{'role':<7}" + "".join(f"{c:>10}" for c in CHANNELS))
            for r in live:
                lines.append(f"{r.marker:<9}{_MODULE_TAG.get(module_of(r.marker), '?'):<4}{r.role:<7}"
                             + "".join(_s(res.channel_skill[c].get(r.marker, float('nan')), 10) for c in CHANNELS))
            if res.channel_cross:
                lines.append(f"{'mean over cross-module markers':<20}"
                             + "".join(_s(res.channel_cross.get(c, float('nan')), 10) for c in CHANNELS))
            lines.append(f"(reroute check: max |diff|/NORM_SCALE {res.hook_err:.1e})")
    return "\n".join(lines)


def settings_summary(st: CalibrationSettings, model: ModularPhysiologyNetwork) -> str:
    pm, ps = prior_stats(model)
    prior = (f"trained prior (diag N, weight {st.prior_weight})" if pm is not None
             else f"iso-L2 {st.l2_weight} toward the start (no trained prior)")
    return (f"max_steps={st.max_steps} lr={st.lr} patience={st.patience} holdout={st.holdout_fraction:.0%} "
            f"accept>={st.accept_rel_improvement:.0%} huber={st.huber_delta} soft_norm={st.soft_norm_weight}"
            f"@{st.soft_norm_radius} max_norm={st.max_norm} prior: {prior}")


def result_json(res: SetResult) -> dict[str, Any]:
    def clean(x: Any) -> Any:
        if isinstance(x, float) and (math.isnan(x) or math.isinf(x)):
            return None
        if isinstance(x, dict):
            return {str(k): clean(v) for k, v in x.items()}
        if isinstance(x, (list, tuple)):
            return [clean(v) for v in x]
        return x
    return clean({
        "source": res.source, "a_markers": res.a_markers, "b_markers": res.b_markers,
        "accepted": res.accepted, "units": len(res.units),
        "reasons": dict(Counter(u.reason for u in res.units)),
        "headline": res.headline, "headline_cross_module": res.headline_cross,
        "headline_same_module": res.headline_same, "headline_accepted": res.headline_accepted,
        "interval90": list(res.interval) if res.interval else None,
        "interval90_cross_module": list(res.interval_cross) if res.interval_cross else None,
        "control_checkin_skill": res.control_checkin, "control_ok": res.control_ok,
        "channels": res.channel_skill, "channels_cross_module_mean": res.channel_cross,
        "channel_reroute_err": res.hook_err,
        "rows": [r.__dict__ for r in res.rows],
        "unit_detail": [{
            "unit": u.unit, "accepted": u.accepted, "reason": u.reason, "steps": u.steps,
            "emb_dist_prior": u.emb_dist_prior, "emb_dist_cal": u.emb_dist_cal,
            "emb_norm": u.emb_norm, "seconds": u.seconds,
            # per (marker, span) sums of |error|: enough to redo any pooled number offline
            "cells": {f"{mk}/{sp}": {"n": t.n, "cal": t.cal, "prior": t.prior, "init": t.init}
                      for (mk, sp), t in u.cells.items()},
            "channel_cells": {f"{ch}/{mk}": {"n": t.n, "cal": t.cal, "prior": t.prior}
                              for (ch, mk), t in u.channels.items()},
        } for u in res.units],
    })


# ------------------------------------------------------------------ drivers


def run_synthetic(
    model: ModularPhysiologyNetwork, sets: Sequence[Sequence[str]], held_out: Sequence[str],
    protocol: Protocol, settings: CalibrationSettings, *, n_patients: int, seed: int,
    emb_sd: float = 0.1, emb_scale: float = 1.0, init: str = "person", obs_noise: float = 0.0,
    table: torch.Tensor | None = None, channels: bool = True, log: Any = print,
) -> list[SetResult]:
    e_prior = prior_embedding(model)
    embs = draw_embeddings(model, n_patients, seed=seed, emb_sd=emb_sd, scale=emb_scale, table=table)
    patients: list[Patient] = []
    person_ok = True
    for i, e in enumerate(embs):
        p, ok = make_patient(model, i, e, protocol, init)
        person_ok &= ok
        patients.append(p)
    if init == "person" and not person_ok:
        log("WARNING: person-specific setpoint decoders unavailable on this model; using the typical "
            "initial state for every patient")
    results = []
    for a in sets:
        b, dropped = held_out_markers(a, held_out)
        units = []
        for p in patients:
            u = score_patient(model, p, protocol, a, b, e_prior=e_prior, settings=settings,
                              obs_noise=obs_noise, noise_seed=seed, channels=channels)
            units.append(u)
            log(f"  [{'+'.join(a)}] patient {p.index + 1}/{len(patients)}  {u.seconds:5.1f}s  "
                f"{'ACCEPTED' if u.accepted else 'rejected':8} ({u.reason}, {u.steps} steps)  "
                f"||e_true||={float(p.embedding.norm()):.2f}  "
                f"dist prior->cal {u.emb_dist_prior:.3f}->{u.emb_dist_cal:.3f}")
        results.append(build_set_result("synthetic", units, a, b, dropped))
    return results


def run_real(
    model: ModularPhysiologyNetwork, episodes: Sequence[BenchmarkEpisode],
    sets: Sequence[Sequence[str]], held_out: Sequence[str] | None, settings: CalibrationSettings,
    channels: bool = True, log: Any = print,
) -> list[SetResult]:
    e_prior = prior_embedding(model)
    available = episode_markers(episodes)
    results = []
    for a in sets:
        # Unrequested held-out = every other marker with data; dropping A from it is not news.
        b, dropped = held_out_markers(a, [m for m in (held_out or available) if m in available])
        dropped = dropped if held_out else []
        if not b:
            log(f"  [{'+'.join(a)}] no held-out marker with data in these episodes; skipped")
            continue
        units = []
        for k, ep in enumerate(episodes):
            u = score_episode(model, ep, a, b, e_prior=e_prior, settings=settings, channels=channels)
            if u is None:
                log(f"  [{'+'.join(a)}] episode {ep.user_id}: fewer than 2 check-in times of {a}; skipped")
                continue
            units.append(u)
            log(f"  [{'+'.join(a)}] episode {k + 1}/{len(episodes)} {ep.user_id}  {u.seconds:6.1f}s  "
                f"{'ACCEPTED' if u.accepted else 'rejected':8} ({u.reason}, {u.steps} steps)")
        if units:
            results.append(build_set_result("real", units, a, b, dropped))
    return results


def parse_sets(text: str) -> list[tuple[str, ...]]:
    """``"glucose,glucose+hr"`` -> ``[("glucose",), ("glucose", "hr")]``."""
    sets = [tuple(m.strip() for m in grp.split("+") if m.strip()) for grp in text.split(",") if grp.strip()]
    for s in sets:
        for m in s:
            if m not in MARKER_INDEX:
                raise argparse.ArgumentTypeError(f"unknown marker {m!r}")
    return sets


def parse_markers(text: str) -> list[str]:
    ms = [m.strip() for m in text.split(",") if m.strip()]
    for m in ms:
        if m not in MARKER_INDEX:
            raise argparse.ArgumentTypeError(f"unknown marker {m!r}")
    return ms


BANNER_UNTRAINED = (
    "UNTRAINED MODEL: {what}. These numbers measure the MACHINERY (calibrate -> accept/reject -> predict ->\n"
    "score -> control), not the model. Amplification on an untrained network has no reason to be positive\n"
    "or negative, and says nothing about a trained one. Pass a checkpoint for the real question.")


def main(argv: Sequence[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("model", nargs="?", help="checkpoint .pt (local path or gs://...); omit for a FRESH untrained model")
    ap.add_argument("--sets", type=parse_sets, default=list(DEFAULT_SETS),
                    help="calibrated sets A, comma-separated, '+' within a set (default glucose,glucose+hr)")
    ap.add_argument("--held-out", type=parse_markers, default=None,
                    help=f"held-out markers B (default {','.join(DEFAULT_HELD_OUT)} synthetic; all other "
                         "markers with data on real episodes). Anything also in A is dropped for that A.")
    ap.add_argument("--patients", type=int, default=3, help="synthetic patients (default 3)")
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--emb-sd", type=float, default=0.1, help="N(0, sd^2) embeddings when there is no trained prior")
    ap.add_argument("--emb-scale", type=float, default=1.0, help="multiplier on prior_std when drawing from the trained prior")
    ap.add_argument("--patients-from", choices=("prior", "table"), default="prior",
                    help="'table': the checkpoint's own trained rows (realistic covariance, but in-sample)")
    ap.add_argument("--init", choices=("person", "typical"), default="person",
                    help="synthetic initial state: this patient's own setpoints (as iter89) or NORM_CENTER")
    ap.add_argument("--noise", type=float, default=0.0, help="sensor noise on A's observations, in multiples of sigma_obs")
    ap.add_argument("--no-channels", action="store_true",
                    help="skip the transfer-channel decomposition (own / coupling / gut; ~8 extra no-grad rollouts per unit)")
    ap.add_argument("--duration", type=int, default=120)
    ap.add_argument("--cal-end", type=int, default=60)
    ap.add_argument("--obs-every", type=int, default=10)
    ap.add_argument("--score-every", type=int, default=5)
    ap.add_argument("--start-time", type=float, default=420.0, help="minute of day at t=0")
    ap.add_argument("--meal-at", type=float, default=10.0, help="meal minute (negative: fasting)")
    ap.add_argument("--steps", type=int, default=16, help="calibration max_steps (the gate runs 512)")
    ap.add_argument("--gate-settings", action="store_true",
                    help="CalibrationSettings.from_env() untouched: exactly what the gate and the server run")
    ap.add_argument("--authority", type=float, default=0.0,
                    help="FRESH model only: re-draw the zero-init per-person head outputs from N(0, STD^2)")
    ap.add_argument("--dataset", help="benchmark dataset JSON: also run PART 2 on its real episodes")
    ap.add_argument("--source", default="cgm_real", help="episode source to score (default cgm_real; 'all' for none)")
    ap.add_argument("--max-episodes", type=int, default=3, help="real episodes to score (0 = all)")
    ap.add_argument("--no-synthetic", action="store_true", help="skip PART 1")
    ap.add_argument("--json", help="write every number to this path")
    ap.add_argument("--threads", type=int, default=1, help="torch intra-op threads (1 is fastest on a loaded box)")
    args = ap.parse_args(argv)

    torch.set_num_threads(max(1, args.threads))
    trained = bool(args.model)
    if not trained and args.patients_from == "table":
        ap.error("--patients-from table needs a checkpoint (the table is part of it)")
    if trained and args.authority:
        ap.error("--authority re-draws the heads of a FRESH model; a checkpoint's heads are what is being measured")
    table = None
    if trained:
        model, blob = load_model(args.model)
        if args.patients_from == "table":
            state = blob.get("embeddings_state")
            if not state or "weight" not in state:
                raise SystemExit("--patients-from table: this checkpoint carries no embeddings_state")
            table = state["weight"].float()
        what = None
    else:
        model = fresh_model(args.seed, args.authority)
        what = (f"fresh ModularPhysiologyNetwork, seed {args.seed}, "
                + (f"per-person heads re-drawn at std {args.authority}" if args.authority > 0
                   else "per-person heads zero-initialised: the embedding reaches the trajectory only "
                        "through the gut kernel"))

    base = CalibrationSettings.from_env() if args.gate_settings else CalibrationSettings.from_env(max_steps=args.steps)
    protocol = Protocol(duration_min=args.duration, cal_end_min=args.cal_end, obs_every_min=args.obs_every,
                        score_every_min=args.score_every, start_time_minutes=args.start_time,
                        meal_at_min=args.meal_at)
    try:
        from pulse.benchmark import _git_sha
        raw = _git_sha()
        sha = raw[:12] + ("-dirty" if raw.endswith("-dirty") else "")
    except Exception:    # a header line must never be the reason a probe does not run
        sha = "unknown"
    print("amplification probe: does calibrating on markers A improve prediction of markers B it never saw?")
    print("skill = 1 - MAE_calibrated / MAE_prior_mean  (baseline: the prior-mean embedding, i.e. NOT calibrating;")
    print("        the gate's skill is 1 - MAE/max(persistence, sigma_obs)). 0 = no change, <0 = made it worse.")
    print("gate  = 1 - MAE_cal / max(MAE_prior, sigma_obs); '*' = prior-mean error already under sensor noise.")
    print("+/-/= = patients (episodes) improved / worse / tied. MAE_init = persistence from the initial state.")
    print("role: 'fit pts' / 'calibrated' = A (control: in-sample / whole scored span); held-out B is 'cross' if no A marker")
    print("      shares its module (the PRD's coupled-module claim) or 'same' if one does (insulin after glucose).")
    if not args.no_channels:
        print("CHANNELS: the calibrated embedding is shown to only part of the model (the rest keeps the prior mean):")
        for c in CHANNELS:
            print(f"  {c:<9}{CHANNEL_HELP[c]}")
    print(f"model: {sum(p.numel() for p in model.parameters()):,} parameters, "
          f"{len(model.embedding_projections)} embedding projections; code at {sha}")
    print(f"calibration: {settings_summary(base, model)}")
    if not trained:
        print(BANNER_UNTRAINED.format(what=what))

    all_results: list[SetResult] = []
    header: dict[str, Any] = {"model": args.model, "trained": trained, "settings": base.as_dict(),
                              "args": {k: v for k, v in vars(args).items() if k != "sets"},
                              "sets": ["+".join(s) for s in args.sets]}
    if not args.no_synthetic:
        b_req = args.held_out or list(DEFAULT_HELD_OUT)
        src = ("rows of the trained table" if table is not None else
               f"trained prior N(mu, sigma^2) x{args.emb_scale}" if prior_stats(model)[0] is not None else
               f"N(0, {args.emb_sd}^2)")
        print(f"\nPART 1 -- synthetic patients: {args.patients} drawn from {src}; observations and held-out truth "
              f"generated by the model itself (zero model error{'' if not args.noise else f', A noise {args.noise} sigma_obs'}).")
        print(f"protocol: {protocol.duration_min} min from {protocol.start_time_minutes / 60:.0f}:00, "
              f"{'fasting' if not protocol.meals() else f'meal {protocol.meal_carbs_g:.0f}/{protocol.meal_fats_g:.0f}/{protocol.meal_proteins_g:.0f} g C/F/P at t={protocol.meal_at_min:.0f}'}"
              f"; A observed every {protocol.obs_every_min} min over (0,{protocol.cal_end_min}], scored every "
              f"{protocol.score_every_min} min ('window' <= {protocol.cal_end_min} < 'ahead'); init={args.init}")
        t0 = time.time()
        syn = run_synthetic(model, args.sets, b_req, protocol, base, n_patients=args.patients, seed=args.seed,
                            emb_sd=args.emb_sd, emb_scale=args.emb_scale, init=args.init,
                            obs_noise=args.noise, table=table, channels=not args.no_channels)
        for r in syn:
            print(render_set(r))
        print(f"\n(synthetic part took {time.time() - t0:.0f}s)")
        all_results += syn
    if args.dataset:
        eps = load_benchmark_dataset(args.dataset)
        if args.source != "all":
            eps = [e for e in eps if e.source == args.source]
        if args.max_episodes > 0:
            eps = eps[:args.max_episodes]
        if not eps:
            print(f"\nPART 2 -- no episodes with source={args.source!r} in {args.dataset}")
        else:
            subj = len({subject_of(e.user_id) for e in eps})
            print(f"\nPART 2 -- real episodes: {len(eps)} of source {args.source!r} from {subj} subject(s) "
                  f"(read as n={subj}); calibration check-ins of A only; B scored on its own check-ins "
                  "('window') and eval measurements ('ahead').")
            t0 = time.time()
            real = run_real(model, eps, args.sets, args.held_out, base, channels=not args.no_channels)
            for r in real:
                print(render_set(r))
            print(f"\n(real part took {time.time() - t0:.0f}s)")
            all_results += real
    if all_results:
        print("\nSUMMARY (skill = 1 - MAE_cal/MAE_prior_mean; 0 = calibration changed nothing the held-out markers could feel)")
        for r in all_results:
            h = r.headline
            mean = f"{h['mean']:+.3f}" if h["n_markers"] else "  n/a "
            ctrl = f"{r.control_checkin:+.2f}" if not math.isnan(r.control_checkin) else " n/a "
            cross = (f"  cross-module {r.headline_cross['mean']:+.3f}" if r.headline_cross["n_markers"] else "")
            chan = ("" if not r.channel_cross or r.hook_err > HOOK_TOL else
                    "  via " + " ".join(f"{c} {r.channel_cross[c]:+.2f}" for c in CHANNELS[1:] if c in r.channel_cross))
            print(f"  {r.source:<9} A={'+'.join(r.a_markers):<11} accepted {r.accepted}/{len(r.units)}  "
                  f"held-out mean skill {mean} over {h['n_markers']} markers ({h['n_flat']} flat){cross}{chan}  "
                  f"control (in-sample) {ctrl} {'ok' if r.control_ok else 'NOT OK'}")
    if not trained:
        print("\n" + BANNER_UNTRAINED.format(what=what))
    if args.json:
        Path(args.json).write_text(json.dumps({**header, "results": [result_json(r) for r in all_results]}, indent=1))
        print(f"wrote {args.json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
