#!/usr/bin/env python3
"""Emit TypeScript marker catalogs from pulse.types.MARKERS.

Run from anywhere:
  python3 apps/pulse/engine/scripts/generate_markers.py

Or from apps/pulse/engine:
  python3 scripts/generate_markers.py

Edits belong in pulse/types.py only; then re-run this script.
"""

from __future__ import annotations

import sys
from pathlib import Path

_ENGINE_ROOT = Path(__file__).resolve().parent.parent
if str(_ENGINE_ROOT) not in sys.path:
    sys.path.insert(0, str(_ENGINE_ROOT))

from pulse.types import MARKERS  # noqa: E402

_PULSE_ROOT = _ENGINE_ROOT.parent
_BACKEND_OUT = _PULSE_ROOT / "backend" / "src" / "markers" / "markers.generated.ts"
_FRONTEND_OUT = _PULSE_ROOT / "frontend" / "src" / "markers.generated.ts"

_HEADER = """/* AUTO-GENERATED by apps/pulse/engine/scripts/generate_markers.py — do not edit. */

"""


def _ts_string(s: str) -> str:
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _ts_num(x: float) -> str:
    if float(x).is_integer():
        return str(int(x))
    return repr(float(x))


def _emit_backend() -> str:
    lines = [
        _HEADER.rstrip(),
        "export type MarkerSystem = 'metabolic' | 'hormonal' | 'vital';",
        "",
        "export interface MarkerDefinition {",
        "  id: string;",
        "  name: string;",
        "  unit: string;",
        "  system: MarkerSystem;",
        "  typical: number;",
        "  min: number;",
        "  max: number;",
        "  color: string;",
        "}",
        "",
        "export const MARKERS: MarkerDefinition[] = [",
    ]
    for m in MARKERS:
        lines.append("  {")
        lines.append(f"    id: {_ts_string(m.id)},")
        lines.append(f"    name: {_ts_string(m.name)},")
        lines.append(f"    unit: {_ts_string(m.unit)},")
        lines.append(f"    system: {_ts_string(m.ui_system)},")
        lines.append(f"    typical: {_ts_num(m.typical)},")
        lines.append(f"    min: {_ts_num(m.min)},")
        lines.append(f"    max: {_ts_num(m.max)},")
        lines.append(f"    color: {_ts_string(m.color)},")
        lines.append("  },")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def _emit_frontend() -> str:
    lines = [
        _HEADER.rstrip(),
        "import type { MarkerDef } from './marker-types';",
        "",
        "export const MARKERS: MarkerDef[] = [",
    ]
    for m in MARKERS:
        lines.append("  {")
        lines.append(f"    id: {_ts_string(m.id)},")
        lines.append(f"    name: {_ts_string(m.name)},")
        lines.append(f"    unit: {_ts_string(m.unit)},")
        lines.append(f"    system: {_ts_string(m.ui_system)},")
        lines.append(f"    min: {_ts_num(m.min)},")
        lines.append(f"    max: {_ts_num(m.max)},")
        lines.append(f"    typical: {_ts_num(m.typical)},")
        lines.append(f"    color: {_ts_string(m.color)},")
        lines.append(f"    icon: {_ts_string(m.icon)},")
        lines.append("  },")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    _BACKEND_OUT.parent.mkdir(parents=True, exist_ok=True)
    _FRONTEND_OUT.parent.mkdir(parents=True, exist_ok=True)
    _BACKEND_OUT.write_text(_emit_backend(), encoding="utf-8")
    _FRONTEND_OUT.write_text(_emit_frontend(), encoding="utf-8")
    print(f"Wrote {_BACKEND_OUT.relative_to(_PULSE_ROOT)}")
    print(f"Wrote {_FRONTEND_OUT.relative_to(_PULSE_ROOT)}")


if __name__ == "__main__":
    main()
